name:                advent2018 
version:             0.1.0.0
github:              "rszczers/AdventOfCode2018"
license:             BSD3
author:              "Rafał Szczerski"
maintainer:          "rafal.szczerski@gmail.com"
copyright:           "(c) 2018 Rafał Szczerski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experimental

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rszczers/advent2018#readme>

dependencies:
- base >= 4.7 && < 5
- tasty-hspec
- hspec 
- hspec-core 
- QuickCheck 
- tagged 
- tasty 
- tasty-quickcheck 
- tasty-smallcheck 
- wreq
- lens
- text
- bytestring
- containers
- mtl
- Unique
- extra
- hashable
- unordered-containers

library:
  source-dirs: src

executables:
  advent2018-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2018

tests:
  advent2018-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2018
