name:                advent2019
version:             0.1.0.0
github:              "rszczers/advent2019"
license:             BSD3
author:              "Rafał Szczerski"
maintainer:          "rafal@szczerski.pl"
copyright:           "2019 Rafał Szczerski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rszczers/advent2019#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- text
- mtl
- vector
- lens
- parsec

library:
  source-dirs: src

executables:
  advent2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2019

tests:
  advent2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2019
